# Generated by Django 4.2 on 2026-06-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='leave/'),
        ),
    ]
