# Generated by Django 4.2 on 2026-06-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_alter_leave_leave_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='logo',
            new_name='attachment',
        ),
    ]
