# Generated by Django 4.2 on 2026-06-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0004_rename_logo_leave_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day')], max_length=20),
        ),
    ]
