# Generated by Django 4.2 on 2026-06-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0005_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Emergency Leave', 'Emergency Leave'), ('Medical Leave', 'Medical Leave'), ('Half Day', 'Half Day')], max_length=20),
        ),
    ]
