# Generated by Django 4.2 on 2026-06-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0008_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_duration',
            field=models.CharField(choices=[('Full Day', 'Full Day'), ('First Half', 'First Half'), ('Second Half', 'Second Half')], default='Full Day', max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Emergency Leave', 'Emergency Leave'), ('Medical Leave', 'Medical Leave')], max_length=20),
        ),
    ]
