# Generated by Django 4.2 on 2026-06-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(
    decimal_places=2,
    default=0,
    max_digits=10
)
        ),
    ]
