# Generated by Django 4.2 on 2026-06-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.CharField(max_length=10),
        ),
    ]
