# Generated by Django 4.2 on 2026-06-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='original_password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
