# Generated by Django 4.2 on 2026-06-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_companydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pf_percentage',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
        ),
    ]
